# Generated by Django 3.0.5 on 2020-06-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Top', '0002_auto_20200625_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.TextField(db_index=True, max_length=30, unique=True, verbose_name='Название'),
        ),
    ]
