# Generated by Django 3.0.5 on 2020-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Top', '0003_auto_20200625_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(blank=True, max_length=48, null=True, verbose_name='Название статьи'),
        ),
    ]
